### ISSUE TITLE
demo does not work in Xamarin

### ISSUE THREAD

**Issue by helderfc** [regulaforensics/Xamarin-DocumentReader#1]
This demo does not work in Xamarin, it as different code for Android and different code for IOS, and does not explain how to use in a Xamarin Forms .

Can someone explain how to put it to work from a XAML Xamarin Forms Portable App??

**Comment by syakimchik** [comment]
Yes, we provided simple demo how Xamarin Developers can use our product. In future, we're planning to  extend current example. But you can take a look at [Xamarin Forms Samples](https://github.com/xamarin/xamarin-forms-samples) and find how you can use one UI and different logic for iOS and Android.
