### ISSUE TITLE
[FR] .NET 8 support (latest version of .NET MAUI)

### ISSUE THREAD

**Issue by yurkinh** [regulaforensics/Xamarin-DocumentReader#23]
Are there any plans to support .NET 8 and the latest version of .NET MAUI

**Comment by vyakimchik** [comment]
Hello,

Support for the .NET MAUI [has been implemented](https://docs.regulaforensics.com/develop/doc-reader-sdk/release-notes/doc-reader-release-notes-6-8/) and already available in the latest version. Please update. Thanks!
