### ISSUE TITLE
Face Matching

### ISSUE THREAD

**Issue by Novotnde** [regulaforensics/Xamarin-DocumentReader#3]
Hello, 

I have been wondering if you could please advise me where to find an example for your custom setting for Face matching option. I have found most of your custom setting on this website https://docs.regulaforensics.com/xamarin/custom-settings however Face Matching seems to be missing. Can you advise please?

**Comment by vyakimchik** [comment]
Hello.

Unfortunately, we haven't published the SDK for face matching for Xamarin yet. It's in development.

**Comment by Novotnde** [comment]
Hello, oh I see. Thank you for your quick response. Do you have any rough idea when it will be ready to publish?

**Comment by vyakimchik** [comment]
Unfortunately, we can't name the exact date at the moment.

**Comment by syakimchik** [comment]
Face SDK sample you can find [here](https://github.com/regulaforensics/Xamarin-FaceSDK)
