### ISSUE TITLE
Sample App Android: Could not find any available provisioning profiles for DocumentReaderSample on iOS.

### ISSUE THREAD

**Issue by Lug16** [regulaforensics/Xamarin-DocumentReader#30]
Hi,

I just downloaded your "DocumentReaderSample" App, and wanted to run it on Android. Unfortunately building is not possible because the following message:

`Build with surface heuristics started at 22:11:00
Use build tool: /usr/local/share/dotnet/sdk/8.0.401/MSBuild.dll
CONSOLE: MSBuild version 17.11.4+37eb419ad for .NET
CONSOLE: Build started 15/10/2024 10:11:00 PM.
CONSOLE: Project "/var/folders/v3/cwf7bv194bg4_2qxtm8gvglw0000gn/T/Desituh.proj" on node 1 (default targets).
CONSOLE: ControllerTarget:
CONSOLE:   Run controller from /Applications/Rider.app/Contents/lib/ReSharperHost/JetBrains.Platform.MsBuildTask.v17.dll
0>------- Started building project: DocumentReaderSample
0>Xamarin.Shared.targets(1834,3): Error  : Could not find any available provisioning profiles for DocumentReaderSample on iOS.
        
DocumentReaderSample -> /Users/myuser/Downloads/Xamarin-DocumentReader-master/bin/Debug/net8.0-android/DocumentReaderSample.dll
/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home/bin/javac -J-Dfile.encoding=UTF8 "@/var/folders/v3/cwf7bv194bg4_2qxtm8gvglw0000gn/T/tmpStdJX3.tmp" -target 1.8 -source 1.8 
/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home/bin/java -Xmx1G -classpath /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.113/tools/r8.jar com.android.tools.r8.D8 --debug --min-api 23 --output obj/Debug/net8.0-android/android/bin/ --lib /Users/myuser/Library/Android/sdk/platforms/android-34/android.jar obj/Debug/net8.0-android/android/bin/classes.zip /usr/local/share/dotnet/packs/Microsoft.Android.Ref.34/34.0.113/ref/net8.0/mono.android.jar /usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.113/tools/java_runtime_net6.jar /Users/myuser/.nuget/packages/xamarin.jetbrains.annotations/24.0.1.3/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.annotations-24.0.1.jar /Users/myuser/.nuget/packages/xamarin.kotlin.stdlib/1.9.0.1/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.kotlin.kotlin-stdlib-1.9.0.jar /Users/myuser/.nuget/packages/xamarin.kotlin.stdlib.jdk7/1.9.0.1/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.kotlin.kotlin-stdlib-jdk7-1.9.0.jar /Users/myuser/.nuget/packages/xamarin.kotlin.stdlib.jdk8/1.9.0.1/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.kotlin.kotlin-stdlib-jdk8-1.9.0.jar /Users/myuser/.nuget/packages/xamarin.kotlinx.coroutines.core.jvm/1.7.2.1/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.2.jar /Users/myuser/.nuget/packages/xamarin.kotlinx.coroutines.android/1.7.2.1/buildTransitive/net6.0-android31.0/../../jar/org.jetbrains.kotlinx.kotlinx-coroutines-android-1.7.2.jar /Users/myuser/.nuget/packages/xamarin.google.guava.listenablefuture/1.0.0.14/buildTransitive/net6.0-android31.0/../../jar/guava-listenablefuture.jar /Users/myuser/.nuget/packages/xamarin.androidx.annotation.jvm/1.6.0.2/buildTransitive/net6.0-android31.0/../../jar/androidx.annotation.annotation-jvm.jar /Users/myuser/.nuget/packages/xamarin.androidx.collection/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection.jar /Users/myuser/.nuget/packages/xamarin.androidx.concurrent.futures/1.1.0.14/buildTransitive/net6.0-android31.0/../../jar/androidx.concurrent.concurrent-futures.jar /Users/myuser/.nuget/packages/xamarin.androidx.lifecycle.common/2.6.1.3/buildTransitive/net6.0-android31.0/../../jar/androidx.lifecycle.lifecycle-common.jar /Users/myuser/.nuget/packages/xamarin.androidx.arch.core.common/2.2.0.3/buildTransitive/net6.0-android31.0/../../jar/androidx.arch.core.core-common.jar /Users/myuser/.nuget/packages/xamarin.androidx.resourceinspection.annotation/1.0.1.7/buildTransitive/net6.0-android31.0/../../jar/androidx.resourceinspection.resourceinspection-annotation.jar /Users/myuser/.nuget/packages/xamarin.androidx.constraintlayout.core/1.0.4.6/buildTransitive/net6.0-android31.0/../../jar/androidx.constraintlayout.constraintlayout-core.jar /Users/myuser/.nuget/packages/xamarin.androidx.collection.ktx/1.2.0.9/buildTransitive/net6.0-android31.0/../../jar/androidx.collection.collection-ktx.jar /Users/myuser/.nuget/packages/xamarin.android.glide.disklrucache/4.15.1.2/buildTransitive/net6.0-android31.0/../../jar/disklrucache.jar /Users/myuser/.nuget/packages/xamarin.android.glide.annotations/4.15.1.2/buildTransitive/net6.0-android31.0/../../jar/annotations.jar /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.android-arm/8.0.8/runtimes/android-arm/native/libSystem.Security.Cryptography.Native.Android.jar obj/Debug/net8.0-android/lp/135/jl/classes.jar obj/Debug/net8.0-android/lp/95/jl/classes.jar obj/Debug/net8.0-android/lp/132/jl/classes.jar obj/Debug/net8.0-android/lp/104/jl/classes.jar obj/Debug/net8.0-android/lp/103/jl/classes.jar obj/Debug/net8.0-android/lp/157/jl/classes.jar obj/Debug/net8.0-android/lp/150/jl/classes.jar obj/Debug/net8.0-android/lp/159/jl/classes.jar obj/Debug/net8.0-android/lp/102/jl/classes.jar obj/Debug/net8.0-android/lp/105/jl/classes.jar obj/Debug/net8.0-android/lp/133/jl/classes.jar obj/Debug/net8.0-android/lp/134/jl/classes.jar obj/Debug/net8.0-android/lp/94/jl/classes.jar obj/Debug/net8.0-android/lp/160/jl/classes.jar obj/Debug/net8.0-android/lp/151/jl/classes.jar obj/Debug/net8.0-android/lp/145/jl/classes.jar obj/Debug/net8.0-android/lp/142/jl/classes.jar obj/Debug/net8.0-android/lp/129/jl/classes.jar obj/Debug/net8.0-android/lp/116/jl/classes.jar obj/Debug/net8.0-android/lp/111/jl/classes.jar obj/Debug/net8.0-android/lp/118/jl/classes.jar obj/Debug/net8.0-android/lp/127/jl/classes.jar obj/Debug/net8.0-android/lp/120/jl/classes.jar obj/Debug/net8.0-android/lp/143/jl/classes.jar obj/Debug/net8.0-android/lp/144/jl/classes.jar obj/Debug/net8.0-android/lp/121/jl/classes.jar obj/Debug/net8.0-android/lp/119/jl/classes.jar obj/Debug/net8.0-android/lp/126/jl/classes.jar obj/Debug/net8.0-android/lp/110/jl/classes.jar obj/Debug/net8.0-android/lp/128/jl/classes.jar obj/Debug/net8.0-android/lp/117/jl/classes.jar obj/Debug/net8.0-android/lp/153/jl/classes.jar obj/Debug/net8.0-android/lp/154/jl/classes.jar obj/Debug/net8.0-android/lp/165/jl/classes.jar obj/Debug/net8.0-android/lp/131/jl/classes.jar obj/Debug/net8.0-android/lp/136/jl/classes.jar obj/Debug/net8.0-android/lp/96/jl/classes.jar obj/Debug/net8.0-android/lp/109/jl/classes.jar obj/Debug/net8.0-android/lp/100/jl/classes.jar obj/Debug/net8.0-android/lp/107/jl/classes.jar obj/Debug/net8.0-android/lp/98/jl/classes.jar obj/Debug/net8.0-android/lp/138/jl/classes.jar obj/Debug/net8.0-android/lp/155/jl/classes.jar obj/Debug/net8.0-android/lp/152/jl/classes.jar obj/Debug/net8.0-android/lp/106/jl/classes.jar obj/Debug/net8.0-android/lp/99/jl/classes.jar obj/Debug/net8.0-android/lp/139/jl/classes.jar obj/Debug/net8.0-android/lp/101/jl/classes.jar obj/Debug/net8.0-android/lp/137/jl/classes.jar obj/Debug/net8.0-android/lp/97/jl/classes.jar obj/Debug/net8.0-android/lp/108/jl/classes.jar obj/Debug/net8.0-android/lp/130/jl/classes.jar obj/Debug/net8.0-android/lp/112/jl/classes.jar obj/Debug/net8.0-android/lp/115/jl/classes.jar obj/Debug/net8.0-android/lp/123/jl/classes.jar obj/Debug/net8.0-android/lp/124/jl/classes.jar obj/Debug/net8.0-android/lp/148/jl/classes.jar obj/Debug/net8.0-android/lp/141/jl/classes.jar obj/Debug/net8.0-android/lp/146/jl/classes.jar obj/Debug/net8.0-android/lp/125/jl/classes.jar obj/Debug/net8.0-android/lp/122/jl/classes.jar obj/Debug/net8.0-android/lp/114/jl/classes.jar obj/Debug/net8.0-android/lp/113/jl/classes.jar obj/Debug/net8.0-android/lp/147/jl/classes.jar obj/Debug/net8.0-android/lp/140/jl/classes.jar obj/Debug/net8.0-android/lp/149/jl/classes.jar obj/Debug/net8.0-android/lp/168/jl/libs/F975D0960055A5E3.jar obj/Debug/net8.0-android/lp/161/jl/libs/ED64959F88B22E6D.jar obj/Debug/net8.0-android/lp/169/jl/libs/B71CFF5D5A0B3AEB.jar obj/Debug/net8.0-android/lp/162/jl/libs/2E7FD15AFA9B216B.jar obj/Debug/net8.0-android/lp/124/jl/libs/repackaged.jar --map-diagnostics warning info 
/Users/myuser/Library/Android/sdk/build-tools/35.0.0/zipalign -p 4 "obj/Debug/net8.0-android/android/bin/com.regula.dr.fullrfid.apk" "bin/Debug/net8.0-android//com.regula.dr.fullrfid-Signed.apk" 
/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home/bin/java -jar /Users/myuser/Library/Android/sdk/build-tools/35.0.0/lib/apksigner.jar sign --ks "/Users/myuser/Library/Application Support/Xamarin/Mono for Android/debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 23 --max-sdk-version 34  bin/Debug/net8.0-android/com.regula.dr.fullrfid-Signed.apk 
0>------- Finished building project: DocumentReaderSample. Succeeded: False. Errors: 1. Warnings: 0
Build completed in 00:01:08.660`

Any ideas?

**Comment by vyakimchik** [comment]
Hello. Please make sure that you selected the team, and the provisioning profile and signing certificate are created successfully.

**Comment by Lug16** [comment]
Eventually I re-used a provisioning profile with the App and was able to run it without issues. Thanks
