### ISSUE TITLE
Language if generated results 

### ISSUE THREAD

**Issue by Novotnde** [regulaforensics/Xamarin-DocumentReader#6]
Hi, 

may I ask how do you locally the resources dot document fields? So for example if I scan Id from Czech Republic I get everything in Czech language? If I use android platform I get everything in Czech, however if I use iPad I get document fields in English. 

Do I have to set up the language preference somewhere on the iOs platform?

**Comment by vyakimchik** [comment]
Hello,

The language of the output strings (not values themselves) depends on the locale of your device. If English is set, you'll receive field names in English. If we talk about [values](https://docs.regulaforensics.com/xamarin/results/description-of-results/android#text-result), they can be as [Latin](https://docs.regulaforensics.com/xamarin/enumerations/android/lcid), as [non-Latin](https://docs.regulaforensics.com/xamarin/enumerations/android/lcid). [`lcid`](https://docs.regulaforensics.com/xamarin/results/description-of-results/android#text-result) of results indicates LCID enum value.

**Comment by Novotnde** [comment]
Hi, not output value like "Czech Republic" but the field Descriptor like Nationality. However I have everything set to Czech and still the field descriptors are in English.

**Comment by vyakimchik** [comment]
It should work if you added this language to the project and your device uses it globally. Could you please clarify if it can be reproduced in our demo project which is available in this repository?

**Comment by Novotnde** [comment]
Ok, sorry my mistake. Got it working. Thank you

**Comment by vyakimchik** [comment]
Awesome. Thanks for informing us!
