### ISSUE TITLE
Check for originality 

### ISSUE THREAD

**Issue by Novotnde** [regulaforensics/Xamarin-DocumentReader#8]
Hello, 

I have a question is there any way that your sdk will know if I am scanning copied or fake id? 

Kind regards

**Comment by vyakimchik** [comment]
Hello,

Yes, sure. `OverallResult` of the `DocumentReaderResults` contains the results of all checks made inside the SDK: [Android](https://docs.regulaforensics.com/xamarin/results/description-of-results/android), [iOS](https://docs.regulaforensics.com/xamarin/results/description-of-results/ios), such as a document is expired or not, values obtained from different [sources](https://docs.regulaforensics.com/home/faq/general#what-are-visual-zone-mrz-barcode-rfid-chip) are matched or not, barcodes authenticity, and others. Also, we are working on the functionality that will verify the authenticity of documents using the device Regula 1120. If you already have such one, you can try it out how it works for now by downloading the app [here](https://docs.regulaforensics.com/regula-1120).

**Comment by vyakimchik** [comment]
Hello,

Can this issue be closed or anything is missed?

**Comment by Novotnde** [comment]
thank you for your help
